# The URL the site will be built for
base_url = "https://aqoursoro.com"

# 是否自动编译所有 Sass 文件
compile_sass = true

# 是否构建搜索索引
build_search_index = true

theme = "aqoursoro_pixel"

taxonomies = [
    { name = "tags", feed = true },
]

[markdown]
highlight_code = true

# 多语言配置
default_language = "en"

[languages.en.translations]
title = "AqourSoro"
welcome = "Welcome to my website!"
description = "This is AqourSoro's personal site!"
home = "Home"
blog = "Blog"
language = "English"

[languages.cn.translations]
title = "AqourSoro"
welcome = "欢迎来到我的网站！"
description = "这是AqourSoro的个人网站！"
home = "主页"
blog = "博客"
language = "中文"
