# The URL the site will be built for
base_url = "https://aqoursoro.com"

# 是否自动编译所有 Sass 文件
compile_sass = true

# 是否构建搜索索引
build_search_index = true

theme = "aqoursoro_pixel"

default_language = "en"

[markdown]
highlight_code = true



[languages]

[languages.en]
generate_feeds = true # there will be a feed for French content
build_search_index = true
taxonomies = [
    { name = "tags", feed = true },
]


# 多语言配置

[translations]
title = "AqourSoro"
welcome = "Welcome to my website!"
description = "This is AqourSoro's personal site!"
home = "Home"
blog = "Blog"
posts_title = "Blog Posts"

# 中文配置
[languages.cn]
generate_feeds = true
build_search_index = false
taxonomies = [
    { name = "tags", feed = true },
]

[languages.cn.translations]
title = "AqourSoro"
welcome = "欢迎来到我的网站！"
description = "这是AqourSoro的个人网站！"
home = "主页"
blog = "博客"
posts_title = "博客文章"