name: Deploy Zola Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Zola
        run: |
          wget https://github.com/getzola/zola/releases/download/v0.18.0/zola-v0.18.0-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf zola-v0.18.0-x86_64-unknown-linux-gnu.tar.gz
          mv zola /usr/local/bin

      - name: Build Zola site
        run: |
          cd as_blog  # 如果你的 Zola 项目在子目录中
          zola build

      - name: Copy CNAME file
        run: cp as_blog/CNAME as_blog/public/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: as_blog/public
