name: Zola on GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Build and deploy
        run: |
          cd as_blog
          zola build
          echo "Deploying to GitHub Pages..."
          git init
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git checkout -b gh-pages
          cp -r public/* .
          git add .
          git commit -m "Deploy Zola site"
          git push origin gh-pages --force
